### ISSUE TITLE
Automatically upgrade extensions

### ISSUE THREAD

**Issue by mister-glass** [nonoroazoro/vscode-syncing#26]
It would be great if syncing would install extensions ONLY if it's really necessary (i.e. if they are missing), but not if they are outdated. 
For example I've been away from my secondary PC for a week, and when I opened VSCode all my extensions would auto-update as per my VSCode configuration, but when I triggered Syncing to download the settings, it downloaded all outdated extensions, replacing the ones that VSCode auto-updated by itself.
The best possible scenario for Syncing to install extensions, in my opinion, would be to do so only if they are missing, the rest it should leave to VSCode.

**Comment by nonoroazoro** [comment]
The synchronization algorithm of `Syncing` is much like a **version control** system, thus it will keep and upload the exact version of your extensions to your Gist, and install the exact same version of extensions.

This can avoid some issuses introduced by extension upgrade and keep the VSCode's environment stable.

But like you said, this may also cause inconvenience, especially when you try to download settings right after the VSCode auto-updated all the extensions.

Maybe it's time to remove the **version control**? But I don't know whether it's worth yet.

**Comment by mister-glass** [comment]
I'm just talking from my personal experience using Syncing between my work PC and my home PC, and even today for example, when I triggered 
the `Syncing: Download Settings` option, it would try to replace my already updated extensions with the ones from yesterday... I had to close VSCode to stop the process because the whole extension update scenario takes a lot longer than the native process. 
So I'm down to dropping just this piece of logic, when extensions already exist.

**Comment by nonoroazoro** [comment]
@mister-glass I find a unofficial way to check the latest versions of extensions, and I think I will introduce this feature in the next release.

**Comment by alok-mishra** [comment]
I would like to add that this happens to me all the time where I want to download syncing settings, but it overrides latest extension versions with the version that was there when it was last synced.

I am using several different computers and operating systems and this is basically my workflow which I would like to avoid. When I start the vscode, it first updates extensions.  Then I do a syncing download, which gets settings and old extensions, then I have restart vscode and it gets new extension versions again, and then upload syncing settings again.

Yes, if we can either remove extension versioning, or at-least put a setting which doesn't check versions, that would be great!

Thank you!

**Comment by nonoroazoro** [comment]
@alok-mishra I'm sure you'll get this feature asap 😈

**Comment by nonoroazoro** [comment]
@mister-glass @mister-glass , I've released the new version ([latest release](https://github.com/nonoroazoro/vscode-syncing/releases/latest)) for this feature, enjoy!

**Comment by alok-mishra** [comment]
Thank you for the update. I was testing it, and if extensions are already up to date, syncing still tries to download extensions, and asks you to reload.

Even after you reload vscode with all updated settings and extensiosn, and initiate another download, it will again re-download some extensions (I'm assuming it depends on what version is stored in the gist).

Wouldn't it be better to not keep track of any versioning, but only just keep track of what extensions you have installed?  I personally think that would be more minimal.

Thank you again!

**Comment by nonoroazoro** [comment]
@alok-mishra Syncing is relying on the version no longer, so I think you can check the followings:

1. Are there any disabled extensions?
1. Does your VSCode version meet the extension's requirement?

It will lead to a re-download if any of these occurred.

**Comment by alok-mishra** [comment]
@nonoroazoro Ah, if versions aren't there anymore, I wonder why then.. maybe I just need to upload my settings once and it will be fine afterwards.

No, didn't have any disabled extensions. My version of vscode is 1.25.

I just uploaded settings. So next time it does a sync of changes, I'll report back if there is still an issue. Thanks for your help.

**Comment by nonoroazoro** [comment]
@alok-mishra I found a tiny bug there... and I have released a new version to fix it. :sob:

**Comment by alok-mishra** [comment]
@nonoroazoro thank you for keeping looking. I just wanted to report that at-least for me, the issue  still exists but might be only for linux (not sure how that's possible).  I have Windows 7 at work and Linux (Arch) at home.

On the windows machine, if I have already synced, and try to sync again it doesn't re-get downloads. On my linux machine, after I have synced once, a second sync again re-downloads and shows the [Reload] tag next to the extensions that needed updating. After I upload settings, it works as expected afterwards.

I did get the new syncing 1.8.1 on the first sync... not sure if I restarted before trying the second sync. Will make sure when I get home.

**Comment by nonoroazoro** [comment]
@alok-mishra I think I should debug on a Linux machine to figure out the answer.

**Comment by nonoroazoro** [comment]
@alok-mishra I've tested on:

1.  Linux Mint 17.3 x64
1. Ubuntu 16.04 LTS x64
1. Xubuntu 16.04.3
1. Windows 7 x64
1. Mac EI Captian

And... find nothing 😭

**Comment by alok-mishra** [comment]
@nonoroazoro Sorry for sending you on this crazy mission.  I just tried on my Arch Linux installation, and I also didn't see the issue this time.

My sequence this time was: I had one extension that automatically updated.. I reloaded vscode this time, and then did the syncing download. It didn't re-download the extension.

The key might be in the reload of vscode before syncing.. but I could be wrong.  I'll double check next time something updates, and sync without reload.

I'm fine if you close this.. it might not be as big deal.

**Comment by nonoroazoro** [comment]
@alok-mishra VSCode requires a reload after you synchronized the extensions, otherwise the changes will not take effect and Syncing will not able to get the correct extensions' info from VSCode.

So in this case, you should reload the VSCode or Syncing will re-download the extensions. 😸
